panier:
    path:  /
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    path:  /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:  /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }