pagesBundle_adminPages:
    resource: "@PagesBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin/pages/

page:
    path:  /page/{id}
    defaults: { _controller: PagesBundle:Pages:page }

contact:
    path:  /contact
    defaults: { _controller: PagesBundle:Pages:Contact }
    methods:  [GET, POST]