<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 10/12/16
 * Time: 14:43
 */
namespace Ecommerce\EcommerceBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class testType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Ici nous allons faire notre formulaire en PHP
        // le HTML c'est fini
        $builder
            ->add('email', EmailType::class)
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('sexe', ChoiceType::class, array('choices' => array('homme' => '0',
                                                                      'femme' => '1',
                                                                      'autre' => '2'),'preferred_choices' => array('1', '2'),'expanded' => false))
            ->add('contenu', TextareaType::class)
            ->add('date', DateType::class)
            ->add('utilisateurs', EntityType::class, array('class' => 'Utilisateurs\UtilisateursBundle\Entity\Utilisateurs'))
            ->add('pays', CountryType::class)
            ->add('envoyer', SubmitType::class)
        ;

        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'ecommerce_ecommercebundle_test';
    }
}