<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 11/12/16
 * Time: 12:57
 */

namespace Pages\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
}