<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
}
