factures:
    path:    /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures }

facturePDF:
    path:    /profile/factures/PDF/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturePDF }
