routingUtilisateursAdmin:
    resource: "@UtilisateursBundle/Resources/config/routing/routingUtilisateursAdmin.yml"
    prefix: /admin/utilisateurs

factures:
    path:    /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures }

facturePDF:
    path:    /profile/factures/PDF/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturePDF }
